version: '3.8'

services:
  database:
    image: postgres:15
    container_name: akka_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d akka"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../../
      dockerfile: postgresql/deployment/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  postgres_data:
