services:
  postgresDB:
    image: postgres:15
    container_name: postgresDB
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  akka:
    image: saorex/projet-akka:0.1.0
    container_name: akka
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "9000:9000"
    depends_on:
      postgresDB:
        condition: service_healthy

volumes:
  postgres_data:
